<?xml version="1.0"?>
<!DOCTYPE cv [
    <!ELEMENT cv (titre, cvnom, etatcivil, formations, connaissances, professionnel)>
    <!ELEMENT titre (#PCDATA)>
    <!ELEMENT cvnom (#PCDATA)>
    <!ELEMENT etatcivil (nom, prenom, naissance, situation, adresse?, code_postal?, ville?, pays?, telephone?, email?,caracteristiques?)>
    <!ELEMENT caracteristiques (caracteristique+)>
    <!ELEMENT formations (formation+)>
    <!ELEMENT connaissances (technique*, langue*)>
    <!ELEMENT professionnel (experience+)>
    <!ELEMENT nom (#PCDATA)>
    <!ELEMENT prenom (#PCDATA)>
    <!ELEMENT naissance (#PCDATA)>
    <!ELEMENT situation (#PCDATA)>
    <!ELEMENT adresse (#PCDATA)>
    <!ELEMENT code_postal (#PCDATA)>
    <!ELEMENT ville (#PCDATA)>
    <!ELEMENT pays (#PCDATA)>
    <!ELEMENT telephone (#PCDATA)>
    <!ELEMENT email (#PCDATA)>
    <!ELEMENT caracteristique (#PCDATA)>
    <!ATTLIST caracteristique type CDATA #REQUIRED>
    <!ELEMENT formation EMPTY>
    <!ATTLIST formation
        date-iso CDATA #REQUIRED
        date CDATA #REQUIRED
        datefin CDATA #IMPLIED
        intitule CDATA #REQUIRED
        description CDATA #IMPLIED
    >
    <!ELEMENT technique EMPTY>
    <!ATTLIST technique
        type (0 | 1 | 2| 3 | 4 | 5) #REQUIRED
        nom CDATA #REQUIRED
        description CDATA #IMPLIED
    >
    <!ELEMENT langue EMPTY>
    <!ATTLIST langue
        nom CDATA #REQUIRED
        niveau CDATA #REQUIRED
    >
    <!ELEMENT experience (missions, environnement)>
    <!ATTLIST experience
        date-iso CDATA #REQUIRED
        date CDATA #REQUIRED
        datefin CDATA #IMPLIED
        client CDATA #IMPLIED
        entreprise CDATA #REQUIRED
        fonction CDATA #REQUIRED
    >
    <!ELEMENT missions (mission+)>
    <!ELEMENT environnement (technique+)>
    <!ELEMENT mission (#PCDATA)>
    <!ELEMENT personnel (activite*)>
    <!ELEMENT activite (#PCDATA)>
    <!ATTLIST activite
        type CDATA #REQUIRED
        nom CDATA #REQUIRED
        description CDATA #IMPLIED
    >
]>
<cv>
    <titre>Data Engineer</titre>
    <cvnom>Abdullah Daqdoqa</cvnom>
    <etatcivil>
        <nom>Daqdoqa</nom>
        <prenom>Abdullah</prenom>
        <naissance>1993-06-30</naissance>
        <situation>Single</situation>
        <adresse>Nice, France</adresse>
        <code_postal>6560</code_postal>
        <ville>Vallbonne</ville>
        <pays>France</pays>
        <telephone>0749585804</telephone>
        <email>abdullah.daqdoqa@gmail.com</email>
        <!-- characterestics (optinal) -->
        <caracteristiques >
            <!-- attlist type CDATA  required-->
            <caracteristique type="Personal">Pas tres intelligent</caracteristique>
            <caracteristique type="Personal">paresseux</caracteristique>
        </caracteristiques >
    </etatcivil>
    <formations>
        <formation 
            date-iso="date" 
            date="2021" 
            intitule="IDK" 
            description="some random description" 
        />
    </formations>
    <connaissances>
        <technique type="1" nom="IDK" />
        <technique type="1" nom="IDK" description="description" />
        <langue nom="Arabic" niveau="Native" />
        <langue nom="English" niveau="Intermidate" />
        <langue nom="French" niveau="beginner" />
    </connaissances>
    <professionnel>
        <experience date-iso="xs:date" date="2019-09-24" datefin="2020-10-27" entreprise="Mawdoo3" fonction="Software Engineer">
            <missions>
                <mission>1: I do now know what to say</mission>
                <mission>2: I do now know what to say</mission>
            </missions>
            <environnement>
                <technique type="1" nom="PHP" />
            </environnement>
        </experience>
    </professionnel>
</cv>